//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spyhole.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Spyhole.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon Blank {
            get {
                object obj = ResourceManager.GetObject("Blank", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Cancel {
            get {
                object obj = ResourceManager.GetObject("Cancel", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon CheckMark {
            get {
                object obj = ResourceManager.GetObject("CheckMark", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Cut {
            get {
                object obj = ResourceManager.GetObject("Cut", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Doc {
            get {
                object obj = ResourceManager.GetObject("Doc", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Down {
            get {
                object obj = ResourceManager.GetObject("Down", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Download {
            get {
                object obj = ResourceManager.GetObject("Download", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Edit {
            get {
                object obj = ResourceManager.GetObject("Edit", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Exclamation {
            get {
                object obj = ResourceManager.GetObject("Exclamation", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Folder {
            get {
                object obj = ResourceManager.GetObject("Folder", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таблица.
        /// </summary>
        internal static string frmR_lblDataSet {
            get {
                return ResourceManager.GetString("frmR_lblDataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат.
        /// </summary>
        internal static string frmR_Title {
            get {
                return ResourceManager.GetString("frmR_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить в реестр.
        /// </summary>
        internal static string frmS_cmdSave2Reg {
            get {
                return ResourceManager.GetString("frmS_cmdSave2Reg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл трассировки.
        /// </summary>
        internal static string frmS_lblLogFile {
            get {
                return ResourceManager.GetString("frmS_lblLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интервал (в сек.).
        /// </summary>
        internal static string frmS_lblPauseSec {
            get {
                return ResourceManager.GetString("frmS_lblPauseSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сессия (*.sq3).
        /// </summary>
        internal static string frmS_lblSession {
            get {
                return ResourceManager.GetString("frmS_lblSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить окно трассировки.
        /// </summary>
        internal static string frmS_stbClearTT {
            get {
                return ResourceManager.GetString("frmS_stbClearTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запустить трассировку.
        /// </summary>
        internal static string frmS_stbStartTT {
            get {
                return ResourceManager.GetString("frmS_stbStartTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остановить трассировку.
        /// </summary>
        internal static string frmS_stbStopTT {
            get {
                return ResourceManager.GetString("frmS_stbStopTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Счетчик.
        /// </summary>
        internal static string frmS_stlCount {
            get {
                return ResourceManager.GetString("frmS_stlCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры.
        /// </summary>
        internal static string frmS_tcpParam {
            get {
                return ResourceManager.GetString("frmS_tcpParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отладка.
        /// </summary>
        internal static string frmS_tcpTrace {
            get {
                return ResourceManager.GetString("frmS_tcpTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шпион БД.
        /// </summary>
        internal static string frmS_Title {
            get {
                return ResourceManager.GetString("frmS_Title", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon Hand {
            get {
                object obj = ResourceManager.GetObject("Hand", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Info {
            get {
                object obj = ResourceManager.GetObject("Info", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Key {
            get {
                object obj = ResourceManager.GetObject("Key", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Left {
            get {
                object obj = ResourceManager.GetObject("Left", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Magnifier {
            get {
                object obj = ResourceManager.GetObject("Magnifier", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Minus {
            get {
                object obj = ResourceManager.GetObject("Minus", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        internal static string mnuExit {
            get {
                return ResourceManager.GetString("mnuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запустить.
        /// </summary>
        internal static string mnuStart {
            get {
                return ResourceManager.GetString("mnuStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остановить.
        /// </summary>
        internal static string mnuStop {
            get {
                return ResourceManager.GetString("mnuStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры/Отладка.
        /// </summary>
        internal static string mnuTrParam {
            get {
                return ResourceManager.GetString("mnuTrParam", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon Paint {
            get {
                object obj = ResourceManager.GetObject("Paint", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Paste {
            get {
                object obj = ResourceManager.GetObject("Paste", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Plus {
            get {
                object obj = ResourceManager.GetObject("Plus", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Print {
            get {
                object obj = ResourceManager.GetObject("Print", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon QuestionMark {
            get {
                object obj = ResourceManager.GetObject("QuestionMark", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Recycle {
            get {
                object obj = ResourceManager.GetObject("Recycle", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Redo {
            get {
                object obj = ResourceManager.GetObject("Redo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Redo2 {
            get {
                object obj = ResourceManager.GetObject("Redo2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Restart {
            get {
                object obj = ResourceManager.GetObject("Restart", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Right {
            get {
                object obj = ResourceManager.GetObject("Right", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Shotdown {
            get {
                object obj = ResourceManager.GetObject("Shotdown", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap spyhole004 {
            get {
                object obj = ResourceManager.GetObject("spyhole004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon spyhole004i {
            get {
                object obj = ResourceManager.GetObject("spyhole004i", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Standby {
            get {
                object obj = ResourceManager.GetObject("Standby", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Star {
            get {
                object obj = ResourceManager.GetObject("Star", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Text {
            get {
                object obj = ResourceManager.GetObject("Text", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Tools {
            get {
                object obj = ResourceManager.GetObject("Tools", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
